sudo: false
language: erlang
otp_release:
  - R15B03
  - R16B03-1
  - 17.5
  - 18.3
  - 19.3
  - 20.3
  - 21.3
  - 22.3
  - 23.0
env: MAKE_TARGET=ci
before_script:
  - hostname -f
  - cc -v
  - ld -v
  - find .rebar
after_script:
  - find .rebar
matrix:
  include:
    - otp_release: 20.3
      env: MAKE_TARGET=ci-dialyze
  allow_failures:
    - otp_release: 20.3
      env: MAKE_TARGET=ci-dialyze
script: make $MAKE_TARGET
cache:
  directories:
    - .rebar
before_cache:
  - rm -fv .rebar/erlcinfo
  - rm -fv $HOME/.cache/.rebar/erlcinfo
